[[permission]]
identifier = "scope-appdata"
description = """This scope permits access to all files and
list content of top level directories in the `$HOME`folder."""

[[permission.scope.allow]]
path = "$APPLOCALDATA/**"